cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_total, name='cart_total'),
    path('add/<item_id>', views.add_cart, name='add_cart'),
    path('update/<item_id>', views.update_cart, name='update_cart'),
    path('delete/<item_id>', views.delete_cart, name='delete_cart'),

]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import contact, register

from .forms import SignInForm


app_name = "core"


urlpatterns = [
    
    path('contact/', contact, name='contact'),
    path('register/', register, name='register'),
    path('signIn/', auth_views.LoginView.as_view(template_name='core/signIn.html', authentication_form=SignInForm), name='signIn'),
    
]

filter_folk/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import contact, home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', home, name='home'), 
    path('',include('core.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('account/', include('accounts.urls')),
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.search_products, name='search'),
    path('products/', views.products_list, name='inventory'),
    path('newproduct/', views.add_new_product, name='add_new_product' ),
    path('<int:pk>/', views.product_detail, name='product_detail'),
    path('<int:pk>/delete/', views.delete_product, name='delete'),
    path('<int:pk>/edit/', views.edit_product, name='edit'),

]

product/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=225)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.CASCADE, related_name='products')
    sku = models.CharField(max_length=254,null=True,blank=True)
    name = models.CharField(max_length=300)
    description = models.TextField()
    price = models.FloatField()
    image = models.ImageField(upload_to='product_images', blank=True, null=True)

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
    
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
    
    }))
    



class ProfileRegister(UserCreationForm):
    class Meta:
        model = User
        fields = ('firstname','lastname','username', 'email', 'password1', 'password2')

    firstname = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter First Name',
    
    }))

    lastname = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter Last Name',
    
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Enter Email Address',
    
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
    
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
    'placeholder': 'Choose Password',
    
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
    'placeholder': 'Repeat Password',
    
    }))

product/forms.py
from django import forms

from .models import Product

STYLE_CLASSES = 'col-md-6 offset-md-6'

class AddNewProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'name', 'description', 'price', 'image',)

        widgets = {
            'category': forms.Select(attrs={
                'class': STYLE_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': STYLE_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': STYLE_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': STYLE_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': STYLE_CLASSES
            }),
        }


class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'image',)
        widget = {

            'name': forms.TextInput(attrs={
                'class': STYLE_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': STYLE_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': STYLE_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': STYLE_CLASSES
            }),
        }

core/views.py
from django.shortcuts import render, redirect
from product.models import Category, Product
from django.contrib import messages

from .forms import ProfileRegister

# Create your views here.

def home(request):
    return render(request, 'core/home.html')


def contact(request):
    return render(request,'core/contact.html')


def register(request):

    if request.method == 'POST':
        form = ProfileRegister(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/signIn/')
    else:        
        form = ProfileRegister()


    return render(request, 'core/register.html', {
        'form': form
    })
 

product/views.py
from django.contrib.auth.decorators import login_required 
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.db.models import Q
from .models import Product, Category
from .forms import AddNewProductForm, EditProductForm


def products_list(request):
    products = Product.objects.filter()
    for product in products:
        product.price = round(product.price)
    categories = Category.objects.all()
    
    return render(request, 'product/inventory.html', {
        'categories': categories,
        'products': products, 

    })

def search_products(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    products = Product.objects.filter()

    if category_id:
        products = products.filter(category_id=category_id)

    if query:
         products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'product/products.html', {
        'products': products,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),   
    })


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    related_products = Product.objects.filter(category=product.category).exclude(pk=pk)[0:3]

    return render(request, 'product/product_detail.html', {
        'product': product,
        'related_products': related_products
    })



@login_required 
def add_new_product(request):
        if request.method == 'POST':
            form = AddNewProductForm(request.POST, request.FILES)
            
            if form.is_valid():
                product = form.save(commit=False) 
                product.save()

                return redirect('product:product_detail', pk=product.id)
        else:
            form = AddNewProductForm()

        return render(request, 'product/product_form.html',{
            'form': form,
            'title': 'Add New Product',

        })


@login_required
def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()

    return redirect(reverse('home'))


@login_required 
def edit_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    
    if request.method == 'POST':
        form = EditProductForm(request.POST, request.FILES, instance=product)

        if form.is_valid():
            form.save()

            return redirect('product:product_detail', pk=product.id)
    else:        
        form = EditProductForm(instance=product)

    return render(request, 'product/product_form.html', {
        'form': form,
        'title': 'Edit Product',

    })

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block meta %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% endblock %}

    {% block extra_meta %}
    {% endblock %}
        
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <link href="//cdn-images.mailchimp.com/embedcode/classic-061523.css" rel="stylesheet" type="text/css">
        <script src="https://kit.fontawesome.com/f20e77a55a.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
        <script src="https://js.stripe.com/v3/"></script>
        <script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js"></script><script type="text/javascript">(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script></div>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <title>{% block title %}{% endblock %} Filter for Folks!</title>
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light">
                <h1 class="font-weight-bold"><a class="navbar-brand text-info text-uppercase" href="{% url 'home' %}">Filter for Folks</a></h1>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <hr>
                <div class="row align-items-center">
                    <ul class="navbar-nav mr-auto">
                    
                    {% if request.user.is_superuser == True %}
                    
                        <li class="navbar-item"><a href="{% url 'product:add_new_product' %}" class="btn btn-outline-success text-uppercase">Add Product <i class="fas fa-plus-circle"></i></a></li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser == False %}
                    <li class="list-inline-item">
                        <a class="btn btn-outline-secondary text-uppercase {% if grand_total %}text-info font-weight-bold{% else %}text-black{% endif %} nav-link" href="{% url 'cart_total' %}">
                            <div class="text-center">
                                <div><i class="fas fa-shopping-cart fa-lg"></i>
                                    <p class="my-0">
                                        {% if grand_total %}
                                            ${{ grand_total|floatformat:2 }}
                                        {% else %}
                                            $0.00
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </a>
                    </li>
                        {% endif %}
                        {% if request.user.is_authenticated %} 
                            <li class="navbar-item"><a href="{% url 'product:search' %}" class="btn btn-outline-info text-uppercase">Search Product <i class="fas fa-search"></i></a></li>    
                        {% endif %}
                        <li class="navbar-item"><a href="{% url 'account' %}" class="btn btn-outline-secondary text-uppercase">My Profile<i class="far fa-user-circle"></i></a></li> 
                        <li class="navbar-item"><a href="{% url 'account_logout' %}" class="btn btn-outline-warning text-dark text-uppercase">Log Out <i class="fas fa-sign-in-alt"></i></a></li>
                                          
                    {% else %}
                        
                        <li class="navbar-item"><a href="{% url 'account_signup' %}" class="btn btn-outline-secondary text-uppercase">Register<i class="fas fa-hand-pointer"></i></a></li> 
                        <li class="navbar-item"><a href="{% url 'account_login' %}" class="btn btn-outline-warning text-dark text-uppercase">Sign In <i class="fas fa-sign-in-alt"></i></a></li>    
                    {% endif %}
                    

                    </ul>    
                </div>

        </nav>
        <hr>
    </div>
  
    <div>
        
        {% block content %}
        {% endblock %}
    </div>
    
    <footer class="bg-info px-4">
        <div class="container-fluid mt-5 text-center">
            <div class="row">
                <div class="col w-100">
                    <h5 class="font-weight-bold text-light mt-2">About</h5>
                    <p class="text-light">We want people to live longer thanks to great ventilation in their homes </p>
                </div>
                <div class="col w-100">
                    
                        <h4 class="font-weight-bold text-light mt-2">Menu</h4>
                        <div class="row">
                            <div class="col">
                            <ul class="list-unstyled">
                                <li class="list-unstyled"><a href="{% url 'home' %}" class="nav-link text-lg text-warning d-block p-3">Home</a></li>
                                <li class="list-unstyled"><a href="{% url 'core:contact' %}" class="nav-link text-lg text-warning d-block p-3">Contact</a></li>
                                <li class="list-unstyled"><a href="https://www.termsfeed.com/live/1a7cc1bc-3fec-45b9-87a8-a43810a76fdf" class="nav-link text-lg text-warning d-block p-3" target="_blank">Privacy Policy</a></li>                                
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    {% block postloadjs %}
    {% endblock %}
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="container mt-5">
            <h1>Contact Details:</h1>
            <hr>
            <section class="text-center">
                <h4><i class="far fa-envelope"></i> Email:  info@filter4folks.com</h4> 
            </section>
            <br>
            <br>
            <section class="text-center">
                <h4><i class="fas fa-mobile-alt"></i> Phone:  +46 (08) 123-45673 </h4>
            </section>
            <br>
            <br>
            <section class="text-center">
                <h4>Address: <i class="fas fa-map-marker-alt"></i> 123 Main Street, Stockholm, Sweden </h4>
            </section>
            <br>
            <br>
            <div class="row">
                <div class="text-center rounded mx-auto d-block">
                    
                    <img src="https://images.pexels.com/photos/845451/pexels-photo-845451.jpeg?auto=compress&cs=tinysrgb&w=800" class="img-fluid" alt="Customer support">
                    <H3 class="text-right mt-2">We're here to assist your service!</H3>
                </div>
            </div>

    </div>
</div>
<footer class=" bg-light container-wrapper mt-5">
    <div class="container quotes-container content-container">
      <section class="footer">
       <div class="row">
         <div class="col-12 col-md-6">
           <h4 class="text-center">Social</h4>
           <p>Get to know us on social media and our latest product in our inventory</p>
           <a href="https://www.facebook.com/profile.php?id=61561386792798" target="_blank" class="text-dark"><i class="fab fa-facebook-square"></i> Follow us on Facebook!</a>
         </div>
         <div class="col-12 col-md-6 text-center">
           <h4>Subscribe!</h4>
           
           <div id="mc_embed_shell" class="mt-2">
                <div id="mc_embed_signup">
                        <form action="https://herokuapp.us13.list-manage.com/subscribe/post?u=c55ae6b587ad8fb6f51c56d2d&amp;id=2bb581fdc9&amp;f_id=00f957e1f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
                            <div id="mc_embed_signup_scroll"><p><p>Get exclusive offers and discount codes by subscribing to our monthly newsletter</p></hp>
                                <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
                                <div class="mc-field-group"><label for="mce-EMAIL">Email Address <span class="asterisk">*</span></label><input type="email" name="EMAIL" class="required email" id="mce-EMAIL" required="" value=""></div>
                            <div id="mce-responses" class="clear foot">
                                <div class="response" id="mce-error-response" style="display: none;"></div>
                                <div class="response" id="mce-success-response" style="display: none;"></div>
                            </div>
                        <div aria-hidden="true" style="position: absolute; left: -5000px;">
                            /* real people should not fill this in and expect good things - do not remove this or risk form bot signups */
                            <input type="text" name="b_c55ae6b587ad8fb6f51c56d2d_2bb581fdc9" tabindex="-1" value="">
                        </div>
                            <div class="optionalParent">
                                <div class="clear foot">
                                    <input type="submit" name="subscribe" id="mc-embedded-subscribe" class="button" value="Subscribe">
                                    <p style="margin: 0px auto;"><a href="http://eepurl.com/iSWduA" title="Mailchimp - email marketing made easy and fun"><span style="display: inline-block; background-color: transparent; border-radius: 4px;"><img class="refferal_badge" src="https://digitalasset.intuit.com/render/content/dam/intuit/mc-fe/en_us/images/intuit-mc-rewards-text-dark.svg" alt="Intuit Mailchimp" style="width: 220px; height: 40px; display: flex; padding: 2px 0px; justify-content: center; align-items: center;"></span></a></p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
         </div>
       </div>
       <hr>
     </section>
   </div>
 </footer>
{% endblock %}

core/templates/core/home.html
{% extends 'core/base.html' %}
{% block title %}Home | Filter for Folks {% endblock %}
{% block extra_meta %}
    <meta name="description" content="Filter for Folks. Filter for Folks, an online webshop, safe installments of Air Filters, health, fresh, sustainable, enviromental!">
    <meta name="keywords" content="e-commerce, shopping, Filter for Folks, Hardware Store, Air filters, Toolboxes, Services, Long Expertise, Professional Guidance, Radiators, Tools">

    <meta property="og:type" content="article">
    <meta property="og:title" content="Filter for Folks">
    <meta property="og:description" content="Filter for Folks. Filter for Folks, an online hardware store selling all you need from environmental friendly air filters to toolboxes!"> 
    <meta name="image" property="og:image" content="#">
    <meta property="og:image:alt" content="Filter for Folks ecommerce hardware shown on a variety of devices, from mobile to desktop">
    <meta property="og:url" content="https://filter-for-folks-58441ed4952a.herokuapp.com/">
    <meta property="og:site_name" content="Filter for Folks">
{% endblock %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Filter for Folks</title>
</head>
<body>

    <div class="container-fluid mt-5 text-center">

        <div class="row">

            <div class="col-md-6 order-md-2 text-info">
                {% if request.user.is_authenticated %}
                    <h1 id="welcome">Welcome {{ request.user.username }} to Filter for Folks</h1>

                    <ul>
                        <li class="list-unstyled">
                            <p>
                                <strong>
                                    We're here to assist you with the best air ventilation
                                </strong>
                            </p>
                        </li>
                    </ul>
                {% else %}
                <h1>Welcome to Filter for Folks</h1>

                <ul>
                    <li class="list-unstyled">
                        <p>We're here to assist you with the best air ventilation</p>
                    </li>
                </ul>
                {% endif %}

            </div>
        </div>
        <div class="col-md-6 order-md-1">

            <img src="https://images.pexels.com/photos/54300/pexels-photo-54300.jpeg?auto=compress&cs=tinysrgb&w=600" alt="healthy wind">
        </div>

        <div class="row justify-content-end">
            <div class="col-md-6 order-md-1">

                <a href="{% url 'product:inventory' %}" class="btn btn-outline-info btn-lg">
                    <span>
                        <i class="far fa-hand-point-right"></i>
                    </span>
                    <span class="text-uppercase">Our Inventory</span>
                </a>
            </div>

        </div>

    </div>

</body>

</html>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Welcome{% endblock %}
{% block content %}
<div class="container-fluid mt-5 px-4 col w-100">

    <h2><span class="badge badge-primary">Our</span> Air Filters <i class="fas fa-cloud" style="color: #74C0FC;"></i></h2>
    <div class="bg-info mt-3 p-5 text-center">

        <div class="row">
            {% for product in products %}
                    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                        <div class="card h-100">
                            <a href="#">
                                <div class="card">
                                    <div class="card-body">
                                        <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                                        <hr>
                                        <div>
                                            <h2 class="card-title text-dark mt-0">{{ product.name }}</h2>
                                            <p class="card-text text-dark">Price: ${{ product.price}}</p>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
            {% endfor %}
        </div>
        <hr>
        <div class="row text-white bg-dark ml-1 container-fluid">

            <h2><span class="badge badge-primary p-3 ">Filter</span> Categories <i class="fas fa-wind" style="color: #74C0FC;"></i></h2>
            <hr>
            {% for category in categories %}
                    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3 mt-3">
                        <div class="h-100">
                            <div>
                                <a href="">
                                    <div class="row">
                                        <div class="col">

                                            <h6 class="card-title mt-0 text-white">{{ category.name }}:</h6>
                                        </div>
                                        
                                        <div class="col">

                                            <p class="card-text text-warning">{{ category.products.count }}</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
        
    </div>
</div>
{% endblock %}

core/templates/core/products.html
{% extends 'core/base.html' %}
{% block title %}Welcome{% endblock %}
{% block content %}
<div class="container-fluid mt-5 px-4 col w-100">

    <h2><span class="badge badge-primary">Our</span> Inventory</h2>
    <div class="bg-info mt-3 p-5 text-center">

        <div class="row">
            {% for product in products %}
                    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                        <div class="card h-100">
                            <a href="{% url 'product:product_detail' product.id %}">
                                <div class="card">
                                    <div class="card-body">
                                        <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                                        <hr>
                                        <div>
                                            <h2 class="card-title text-dark mt-0">{{ product.name }}</h2>
                                            <p class="card-text text-dark">Price: ${{ product.price}}</p>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
            {% endfor %}
        </div>
        <hr>
        <div class="row text-white bg-dark ml-1 container-fluid">

            <h2>Categories</h2>
            <hr>
            {% for category in categories %}
                    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3 mt-3">
                        <div class="h-100">
                            <div>
                                <a href="">
                                    
                                    <p class="card-title mt-0 text-warning">{{ category.name }}</p>
                                </a>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
        
    </div>
</div>
{% endblock %}

core/templates/core/register.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
            <div class="col px-md-5">
                <h1>Register</h1>
                <p class="text-muted">Please create your account with us at <strong class="text-uppercase">Filter for Folks!</strong></p>
                    <form action="" method="post" class="mt-5">
                        {% csrf_token %}
                
                        {% if form.non_field_errors %}

                        
                        {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}

                        {% endif %}
            
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                    
                    <div class="text-danger">
                        <ul class="list-unstyled">
                            <li>
                                {% for field in form %}
                        
                                {{ field }}
                                {{ field.errors.as_ul }}
                            
                                {% endfor %}

                            </li>
                        </ul>

                    </div>
                    <div class="justify-content-end">
                        <button class="btn btn-lg btn-info rounded-circle text-uppercase justify-content-center mt-4" type="submit">Submit</button>
                    </div>
                    
                </form>
            </div>

        <div class="col px-md-5">
            <div class="rounded mx-auto d-block">
                
                <img src="https://images.pexels.com/photos/8815877/pexels-photo-8815877.jpeg?auto=compress&cs=tinysrgb&w=600" class="img-fluid" alt="Register">
            </div>
        </div>
    </div>

</div>
{% endblock %}

core/templates/core/signIn.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Sign In{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center mt-2">
        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">

            
            
                <h1>Sign In</h1>
                <form action="#" method="post">
                    {% csrf_token %}
                    
                    <div class="mb-3">
                        <label class="inline-block mb-2">Username</label><br>
                        {{ form.username }}
                    </div>
                    <div class="mb-3">
                        <label class="inline-block mb-2">Password</label><br>
                        {{ form.password }}
                    </div>
            
                    {% if form.errors or form.non_field_errors %}
                        <div class="mb-3 p-6 bg-danger rounded">
                            {% for field in form %}
                                {{ field.errors }}
                            {% endfor %}
                            {{ form.non_field_errors }}

                        </div>
                    {% endif %}
                    <button class="btn btn-info rounded-circle text-uppercase justify-content-end mt-4" type="submit">Enter page!</button>
                </form>
        </div>
        <img src="https://images.unsplash.com/photo-1525011268546-bf3f9b007f6a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fFNpZ24lMjBpbnxlbnwwfHwwfHx8MA%3D%3D" class="img-fluid rounded" alt="Sign In">
    </div> 
</div>
{% endblock %}