cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_total, name='cart_total'),
    path('add/<item_id>', views.add_cart, name='add_cart'),
    path('update/<item_id>', views.update_cart, name='update_cart'),
    path('delete/<item_id>', views.delete_cart, name='delete_cart'),

]

filter_folk/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import contact, home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', home, name='home'), 
    path('',include('core.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('account/', include('accounts.urls')),
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.search_products, name='search'),
    path('products/', views.products_list, name='inventory'),
    path('newproduct/', views.add_new_product, name='add_new_product' ),
    path('<int:pk>/', views.product_detail, name='product_detail'),
    path('<int:pk>/delete/', views.delete_product, name='delete'),
    path('<int:pk>/edit/', views.edit_product, name='edit'),

]

product/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=225)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.CASCADE, related_name='products')
    sku = models.CharField(max_length=254,null=True,blank=True)
    name = models.CharField(max_length=300)
    description = models.TextField()
    price = models.FloatField()
    image = models.ImageField(upload_to='product_images', blank=True, null=True)

    def __str__(self):
        return self.name

product/forms.py
from django import forms

from .models import Product

STYLE_CLASSES = 'col-md-6 offset-md-6'

class AddNewProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'name', 'description', 'price', 'image',)

        widgets = {
            'category': forms.Select(attrs={
                'class': STYLE_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': STYLE_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': STYLE_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': STYLE_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': STYLE_CLASSES
            }),
        }


class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'image',)
        widget = {

            'name': forms.TextInput(attrs={
                'class': STYLE_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': STYLE_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': STYLE_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': STYLE_CLASSES
            }),
        }

product/views.py
from django.contrib.auth.decorators import login_required 
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.db.models import Q
from .models import Product, Category
from .forms import AddNewProductForm, EditProductForm


def products_list(request):
    products = Product.objects.filter()
    for product in products:
        product.price = round(product.price)
    categories = Category.objects.all()
    
    return render(request, 'product/inventory.html', {
        'categories': categories,
        'products': products, 

    })

def search_products(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    products = Product.objects.filter()

    if category_id:
        products = products.filter(category_id=category_id)

    if query:
         products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'product/products.html', {
        'products': products,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),   
    })


def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    related_products = Product.objects.filter(category=product.category).exclude(pk=pk)[0:3]

    return render(request, 'product/product_detail.html', {
        'product': product,
        'related_products': related_products
    })



@login_required 
def add_new_product(request):
        if request.method == 'POST':
            form = AddNewProductForm(request.POST, request.FILES)
            
            if form.is_valid():
                product = form.save(commit=False) 
                product.save()

                return redirect('product:product_detail', pk=product.id)
        else:
            form = AddNewProductForm()

        return render(request, 'product/product_form.html',{
            'form': form,
            'title': 'Add New Product',

        })


@login_required
def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()

    return redirect(reverse('home'))


@login_required 
def edit_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    
    if request.method == 'POST':
        form = EditProductForm(request.POST, request.FILES, instance=product)

        if form.is_valid():
            form.save()

            return redirect('product:product_detail', pk=product.id)
    else:        
        form = EditProductForm(instance=product)

    return render(request, 'product/product_form.html', {
        'form': form,
        'title': 'Edit Product',

    })

product/templates/product/inventory.html
{% extends 'core/base.html' %}
{% block title %}Welcome{% endblock %}
{% block content %}
<div class="container-fluid mt-5 px-4 col w-100">

    <h2><strong><span class="badge badge-primary">Total</span></strong> Inventory</h2>
    <div class="bg-info mt-3 p-5 text-center">

        <div id="delivery-banner" class="row text-center">
            <div class="col bg-black text-white">
                <h4 class="logo-font my-1">Free delivery on orders over ${{ free_delivery_threshold }}!</h4>                
            </div>            
        </div>

        <div class="row">
            {% for product in products %}
                    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                        <div class="card h-100">
                            <a href="{% url 'product:product_detail' product.id %}">
                                <div class="card">
                                    <div class="card-body">
                                        <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                                        <hr>
                                        <div>
                                            <h2 class="card-title text-dark mt-0">{{ product.name }}</h2>
                                            {% if user.is_authenticated %}
                                                <p class="card-text text-dark">Price: ${{ product.price}}</p>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
            {% endfor %}
        </div>
        <hr>
        <div class="row text-white bg-dark ml-1 container-fluid">

            <h2>Categories</h2>
            <hr>
            {% for category in categories %}
                    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3 mt-3">
                        <div class="h-100">
                            <div>
                                <a href="">
                                    
                                    <p class="card-title mt-0 text-warning">{{ category.name }}</p>
                                </a>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
        
    </div>
</div>
{% endblock %}

product/templates/product/product_detail.html
{% extends 'core/base.html' %}


{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container my-5">
                {% if product.image %}
                    <a href="" target="_blank">
                        <img class="card-img-top img-fluid rounded" src="{{ product.image.url }}" alt="{{ product.name }}">
                    </a>
                    {% else %}
                    <a href="">
                        <img class="card-img-top img-fluid rounded" src="" alt="">
                    </a>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="mb-5 mt-md-5">
                <h2 class="mb-0">{{ product.name }}</h2>
                <hr>
                {% if user.is_authenticated %}
                    <p class="lead mb-0 text-left font-weight-bold"><strong>Price: </strong> ${{ product.price }}</p>
                {% else %} 
                <a href="{% url 'account_signup' %}" class="btn btn-outline-secondary text-uppercase">Wanna se our prices?</a>
                <p class="text-dark">Register an account with us!</p> 
               <br>
                {% endif %} 
                <br>
                {% if product.description %}
                    <p class="lead mb-1 text-left font-weight">
                        <strong>Product Description:</strong><br>
                    </p>
                    <div>
                        {{ product.description }}
                    </div>
                    
                    <div class="col-md-6 order-md-1 mt-5">
                        {% if request.user.is_superuser == False %}

                            {% if user.is_authenticated %}
                            
                                <form class="form" action="{% url 'add_cart' product.id %}" method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-12">
                                            <p class="mt-3"><strong>Quantity:</strong></p>
                                            
                                            <div class="form-group w-50">
                                                <div class="input-group">
                                                    <input class="form-control qty_input" type="number" name="quantity" value="1" min="1" max="9999" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                                                </div>
                                                <p class="mt-2">*Please enter amount*</p>
                                            </div>
                                        </div>

                                        <div class="col-12">
                                            <a href="{% url 'product:inventory' %}" class="btn btn-outline-black rounded-0 mt-5">
                                                <span class="icon">
                                                    <i class="fas fa-chevron-left"></i>
                                                </span>
                                                <span class="text-uppercase">Keep Shopping</span>
                                            </a>
                                            <input type="submit" class="btn btn-success rounded-0 text-uppercase mt-5" value="Add to Cart">
                                        </div>
                                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                                    </div>
                                </form>
                            {% endif %} 
                                
                        {% endif %} 
                    </div>
                            <div class="col-sm">
                                <p>
                                    <a href="{% url 'product:inventory' %}" class="btn btn-outline-info btn-md">
                                        <span>
                                            <i class="far fa-hand-point-right"></i>
                                        </span>
                                        <span class="text-uppercase">Back to Inventory</span>
                                    </a>

                                </p>
                            </div>
                            
                        </div>
                    </div>
                        
                    
                {% endif %}
            
                {% if request.user.is_superuser == True %}
                    <div class="container">
                        <div class="row">
                            <div class="mb-5 mt-md-5">
                                <p>Please make some changes regarding your product!</p>

                                <a href="{% url 'product:edit' product.id %}" class="btn-outline-info btn-lg">Edit</a>
                                <a href="{% url 'product:delete' product.id %}" class="btn-outline-danger btn-lg">Delete</a>

                            </div>
                {% endif %}

                
                        </div>
                    </div>
            </div>
        </div>
      
        <div class="container-fluid">
            <h2><span class="badge badge-primary">Related</span> products: </h2>
            <div class="row">
                {% for product in related_products %}
                
                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="card h-100">
                                <a href="{% url 'product:product_detail' product.id %}">
                                    <div class="card">
                                        <div class="card-body">
                                            <img src="{{ product.image.url }}" class="card-img-top img-fluid">
                                            <hr>
                                            <div>
                                                <h2 class="card-title text-dark mt-0">{{ product.name }}</h2>
                                                {% if user.is_authenticated %}
                                                    <p class="card-text text-dark">Price: ${{ product.price }}</p>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                
                {% empty %}

                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="card h-100">
                                    <div class="card">
                                        <div class="card-body">
                                            <hr>
                                            <div>
                                                <h2 class="card-title text-dark mt-0"> No related products... </h2>

                                            </div>
                                        </div>
                                    </div>
                            </div>
                        </div>
                
                {% endfor %}
            </div>
        </div>
     

</div>


{% endblock %}

product/templates/product/product_form.html
{% extends 'core/base.html' %}


{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center mt-1">
        <div class="col-sm-12 col-md-8 col-lg-6 col-xl-4">


            <h1 class="font-weight-bold">{{ title }}</h1>
            <img src="https://images.pexels.com/photos/6829535/pexels-photo-6829535.jpeg?auto=compress&cs=tinysrgb&w=600" class="img-fluid rounded" alt="Add new product">

            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}

                <div class="mt-4">
                    {{ form.as_p}}
                </div>
                {% if form.errors or form.non_field_errors %}
                    <div class="mb-3 p-6 bg-danger rounded">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}
                        {{ form.non_field_errors }}

                    </div>
                {% endif %}


                    <div class="col-md-6 order-md-2">

                        <button class="btn-outline-success rounded-circle text-uppercase  mt-5" type="submit">Add Product</button>
                    </div>

            </form>
            
        </div>
        
    </div>
    
</div>

{% endblock %}

product/templates/product/products.html
{% extends 'core/base.html' %}


{% block title %}Search Product {% endblock %}

{% block content %}
<div class="container-fluid">
    
    <div class="row">
        <br>
        <div class="col-4 bg-secondary">
            <form method="get" action="#" class="mt-2">
                <input name="query" class="form-control" placeholder="Find a product of your choice...." aria-label="Find a product of your choice...." aria-describedby="basic-addon2" type="text" value="{{ query }}">
                <button type="submit" class="mt-2 p-3 bg-success">Search</button>
            </form>
            <hr>
            <p class="text-warning">Categories</p>
            <ul class="list-unstyled">
                {% for category in categories %}
                <li class="p-2 mb-2 rounded bg-light {% if category.id == category_id %} bg-primary {% endif %}">
                    <a href="{% url 'product:search' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                </li>
                {% endfor %}
            </ul>
            <hr>
            <p class="text-warning">Clear Filter</p>
            <ul class="list-unstyled">
                <li>
                    <a href="{% url 'product:search' %}" class="mt-2 p-3 text-uppercase bg-danger" type="submit"><p class="text-dark">Default Search</p></a>
                </li>
            </ul>

        </div>
        
        
        <div class="col-8">
            <div class="row">
                {% for product in products %}
                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="card h-100">
                                <a href="{% url 'product:product_detail' product.id %}">
                                    <div class="card">
                                        <div class="card-body">
                                            <img src="{{ product.image.url }}" class="card-img-top img-fluid">
                                            <hr>
                                            <div>
                                                <h2 class="card-title text-dark mt-0">{{ product.name }}</h2>
                                                <p class="card-text text-dark">Price: ${{ product.price}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                {% endfor %}
            </div>
        </div>
      </div>
</div>
{% endblock %}